from __future__ import annotations

RARITY_ORDER = {
    "common": 0,
    "uncommon": 1,
    "rare": 2,
    "very_rare": 3,
}

RARITY_LABELS = {
    "common": "Common",
    "uncommon": "Uncommon",
    "rare": "Rare",
    "very_rare": "Very Rare",
}

RARITY_NOTES = {
    "Crimson Nirnroot": "UESP lists 44 plants in Blackreach and no merchant availability.",
    "Daedra Heart": "UESP lists a small set of guaranteed samples and rare merchant inventory.",
    "Giant's Toe": "UESP treats this as a scarce giant drop with limited merchant access.",
    "Gleamblossom": "UESP lists 2 guaranteed samples and 66 plants in the Forgotten Vale area.",
    "Human Flesh": "UESP lists 14-24 guaranteed samples, no merchant inventory, and low-probability extra sources.",
    "Human Heart": "UESP lists 11 guaranteed samples in Skyrim, plus 5 more with Dawnguard, and no normal merchant inventory.",
    "Ice Wraith Teeth": "UESP classifies this ingredient as rare.",
    "Imp Stool": "UESP classifies this ingredient as rare.",
    "Jazbay Grapes": "UESP classifies this ingredient as rare.",
    "Nirnroot": "UESP lists 22 guaranteed samples, 166 plants, and classifies it as rare.",
    "Poison Bloom": "UESP treats this as a tightly limited Dawnguard ingredient.",
    "Salmon Roe": "UESP lists almost no guaranteed samples, but roe can be farmed from salmon in rivers.",
}

RARITY_BY_NAME = {
    "Abecean Longfin": "common",
    "Ancestor Moth Wing": "uncommon",
    "Ash Creep Cluster": "uncommon",
    "Ash Hopper Jelly": "uncommon",
    "Ashen Grass Pod": "uncommon",
    "Bear Claws": "common",
    "Bee": "common",
    "Beehive Husk": "common",
    "Bleeding Crown": "common",
    "Blisterwort": "common",
    "Blue Butterfly Wing": "common",
    "Blue Dartwing": "common",
    "Blue Mountain Flower": "common",
    "Boar Tusk": "uncommon",
    "Bone Meal": "uncommon",
    "Briar Heart": "rare",
    "Burnt Spriggan Wood": "rare",
    "Butterfly Wing": "common",
    "Canis Root": "common",
    "Charred Skeever Hide": "uncommon",
    "Chaurus Eggs": "uncommon",
    "Chaurus Hunter Antennae": "rare",
    "Chicken's Egg": "common",
    "Creep Cluster": "common",
    "Crimson Nirnroot": "rare",
    "Cyrodilic Spadetail": "common",
    "Daedra Heart": "rare",
    "Deathbell": "common",
    "Dragon's Tongue": "common",
    "Dwarven Oil": "common",
    "Ectoplasm": "uncommon",
    "Elves Ear": "common",
    "Emperor Parasol Moss": "rare",
    "Eye of Sabre Cat": "uncommon",
    "Falmer Ear": "uncommon",
    "Felsaad Tern Feathers": "uncommon",
    "Fire Salts": "uncommon",
    "Fly Amanita": "common",
    "Frost Mirriam": "common",
    "Frost Salts": "uncommon",
    "Garlic": "common",
    "Giant Lichen": "common",
    "Giant's Toe": "rare",
    "Gleamblossom": "rare",
    "Glow Dust": "uncommon",
    "Glowing Mushroom": "common",
    "Grass Pod": "common",
    "Hagraven Claw": "rare",
    "Hagraven Feathers": "rare",
    "Hanging Moss": "common",
    "Hawk Beak": "uncommon",
    "Hawk Feathers": "uncommon",
    "Hawk's Egg": "rare",
    "Histcarp": "common",
    "Honeycomb": "common",
    "Human Flesh": "very_rare",
    "Human Heart": "very_rare",
    "Ice Wraith Teeth": "rare",
    "Imp Stool": "rare",
    "Jazbay Grapes": "rare",
    "Juniper Berries": "common",
    "Large Antlers": "common",
    "Lavender": "common",
    "Luna Moth Wing": "common",
    "Moon Sugar": "uncommon",
    "Mora Tapinella": "common",
    "Mudcrab Chitin": "common",
    "Namira's Rot": "uncommon",
    "Netch Jelly": "uncommon",
    "Nightshade": "common",
    "Nirnroot": "rare",
    "Nordic Barnacle": "uncommon",
    "Orange Dartwing": "common",
    "Pearl": "uncommon",
    "Pine Thrush Egg": "uncommon",
    "Poison Bloom": "rare",
    "Powdered Mammoth Tusk": "rare",
    "Purple Mountain Flower": "common",
    "Red Mountain Flower": "common",
    "River Betty": "uncommon",
    "Rock Warbler Egg": "common",
    "Sabre Cat Tooth": "uncommon",
    "Salmon Roe": "uncommon",
    "Salt Pile": "common",
    "Scaly Pholiota": "common",
    "Scathecraw": "uncommon",
    "Silverside Perch": "common",
    "Skeever Tail": "common",
    "Slaughterfish Egg": "uncommon",
    "Slaughterfish Scales": "uncommon",
    "Small Antlers": "common",
    "Small Pearl": "uncommon",
    "Snowberries": "common",
    "Spawn Ash": "uncommon",
    "Spider Egg": "common",
    "Spriggan Sap": "rare",
    "Swamp Fungal Pod": "uncommon",
    "Taproot": "uncommon",
    "Thistle Branch": "common",
    "Torchbug Thorax": "common",
    "Trama Root": "uncommon",
    "Troll Fat": "uncommon",
    "Tundra Cotton": "common",
    "Vampire Dust": "rare",
    "Void Salts": "rare",
    "Wheat": "common",
    "White Cap": "common",
    "Wisp Wrappings": "rare",
    "Yellow Mountain Flower": "common",
}


def rarity_for_ingredient(name: str) -> dict[str, int | str]:
    tier = RARITY_BY_NAME.get(name, "uncommon")
    return {
        "rarity": tier,
        "rarity_label": RARITY_LABELS[tier],
        "rarity_rank": RARITY_ORDER[tier],
        "rarity_note": RARITY_NOTES.get(
            name,
            "UESP-inspired availability tier based on sample counts, merchant access, and how constrained the ingredient is in-world.",
        ),
    }
